title: Emanuel Malfatti
description: My Personal Stack Problems
author: Agus Makmun
github: https://github.com/ejmalfatti
about: Administrador de Sistemas y Software Libre - SysAdmin IPROSS
disqus_shortname: ejmalfattio
google_analytics: UA-81176710-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/emanuel.malfatti.583"
    - icon: fa-twitter
      link: "https://twitter.com/ejmalfatti"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ejmalfatti/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/ejmalfatti"

share:
  twitter_username: ejmalfatti
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ejmalfatti.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
